-- =============================================================================
-- CLC Sermon Platform — Database Schema
-- Epic 2: Database Schema & Strict Security
-- =============================================================================
-- Run this file in the Supabase SQL Editor to initialize the database.
-- Order of creation matters due to foreign key dependencies.
-- =============================================================================


-- ── Extensions ────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- =============================================================================
-- TABLES
-- =============================================================================

-- ── 1. Preachers ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.preachers (
  id         UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  name       TEXT        NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  public.preachers      IS 'Canonical list of all sermon preachers.';
COMMENT ON COLUMN public.preachers.name IS 'Full display name, e.g. "Apostle Muyiwa Areo".';


-- ── 2. Series ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.series (
  id            UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  name          TEXT        NOT NULL UNIQUE,
  thumbnail_url TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  public.series      IS 'Named sermon series / albums.';
COMMENT ON COLUMN public.series.name IS 'Series title, e.g. "Developing a Strong Human Spirit".';


-- ── 3. Sermons ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.sermons (
  id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Core metadata
  title           TEXT        NOT NULL,
  date_preached   DATE        NOT NULL,
  audio_url       TEXT        NOT NULL,

  -- Relations
  preacher_id     UUID        REFERENCES public.preachers (id) ON DELETE SET NULL,
  series_id       UUID        REFERENCES public.series    (id) ON DELETE SET NULL,

  -- Content
  transcript_text TEXT,                        -- raw .txt content
  ai_summary      TEXT,                        -- Groq-generated summary
  ai_tags         TEXT[]      DEFAULT '{}',    -- Groq-generated topic tags

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  public.sermons                IS 'Master sermon catalog — 1,466 entries (2015–2026).';
COMMENT ON COLUMN public.sermons.audio_url      IS 'Direct Archive.org MP3 link.';
COMMENT ON COLUMN public.sermons.transcript_text IS 'Full verbatim transcript imported from .txt files.';
COMMENT ON COLUMN public.sermons.ai_summary     IS 'Groq LLM-generated 2–3 sentence summary.';
COMMENT ON COLUMN public.sermons.ai_tags        IS 'Array of topic/theme tags generated by Groq.';


-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Speed up filtering by preacher, series, and date (most common query patterns)
CREATE INDEX IF NOT EXISTS idx_sermons_preacher_id   ON public.sermons (preacher_id);
CREATE INDEX IF NOT EXISTS idx_sermons_series_id     ON public.sermons (series_id);
CREATE INDEX IF NOT EXISTS idx_sermons_date_preached ON public.sermons (date_preached DESC);

-- Full-text search index on transcript_text for the discoverability layer (Epic 5)
CREATE INDEX IF NOT EXISTS idx_sermons_transcript_fts
  ON public.sermons
  USING GIN (to_tsvector('english', COALESCE(transcript_text, '')));

-- Full-text search on title
CREATE INDEX IF NOT EXISTS idx_sermons_title_fts
  ON public.sermons
  USING GIN (to_tsvector('english', title));

-- GIN index for ai_tags array lookups
CREATE INDEX IF NOT EXISTS idx_sermons_ai_tags ON public.sermons USING GIN (ai_tags);


-- =============================================================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================================================
-- Strategy:
--   • Public (anon) role: SELECT only — full read access.
--   • Authenticated role: INSERT, UPDATE, DELETE — admin write access.
--   • Service role bypasses RLS by default (used only in migration scripts).
-- =============================================================================

-- ── Enable RLS on all tables ──────────────────────────────────────────────────
ALTER TABLE public.preachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sermons   ENABLE ROW LEVEL SECURITY;


-- ── preachers policies ────────────────────────────────────────────────────────
CREATE POLICY "preachers: public read"
  ON public.preachers FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "preachers: admin insert"
  ON public.preachers FOR INSERT
  TO authenticated
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "preachers: admin update"
  ON public.preachers FOR UPDATE
  TO authenticated
  USING (auth.role() = 'authenticated');

CREATE POLICY "preachers: admin delete"
  ON public.preachers FOR DELETE
  TO authenticated
  USING (auth.role() = 'authenticated');


-- ── series policies ───────────────────────────────────────────────────────────
CREATE POLICY "series: public read"
  ON public.series FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "series: admin insert"
  ON public.series FOR INSERT
  TO authenticated
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "series: admin update"
  ON public.series FOR UPDATE
  TO authenticated
  USING (auth.role() = 'authenticated');

CREATE POLICY "series: admin delete"
  ON public.series FOR DELETE
  TO authenticated
  USING (auth.role() = 'authenticated');


-- ── sermons policies ──────────────────────────────────────────────────────────
CREATE POLICY "sermons: public read"
  ON public.sermons FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "sermons: admin insert"
  ON public.sermons FOR INSERT
  TO authenticated
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "sermons: admin update"
  ON public.sermons FOR UPDATE
  TO authenticated
  USING (auth.role() = 'authenticated');

CREATE POLICY "sermons: admin delete"
  ON public.sermons FOR DELETE
  TO authenticated
  USING (auth.role() = 'authenticated');


-- =============================================================================
-- HELPER: Full-text search function (used by Epic 5 discoverability layer)
-- =============================================================================
-- Usage: SELECT * FROM search_sermons('prayer faith');
CREATE OR REPLACE FUNCTION public.search_sermons(query TEXT)
RETURNS SETOF public.sermons
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT *
  FROM public.sermons
  WHERE
    to_tsvector('english', COALESCE(transcript_text, '')) @@ plainto_tsquery('english', query)
    OR to_tsvector('english', title) @@ plainto_tsquery('english', query)
  ORDER BY
    ts_rank(
      to_tsvector('english', COALESCE(transcript_text, '') || ' ' || title),
      plainto_tsquery('english', query)
    ) DESC;
$$;

-- ── Grant Roles Permissions ───────────────────────────────────────────────────
-- Ensure proper privileges are given to the service_role and authenticated users
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
